# Generated by Django 3.2.4 on 2021-06-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habitacion', models.IntegerField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Eliminado', 'Eliminado')], max_length=20)),
                ('desde', models.CharField(max_length=10)),
                ('hasta', models.CharField(max_length=10)),
                ('facturacion', models.CharField(max_length=250)),
                ('id_cliente', models.CharField(max_length=8)),
                ('monto', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=250)),
            ],
        ),
    ]
